name: integrated_odoo
description: "A new Flutter project."
publish_to: 'none' # This keeps the project private

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  odoo_rpc: ^0.5.8  
  curved_navigation_bar: ^1.0.3  # Use the correct/latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
